name: Tic Tac Toe
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    uses: MichaelDiers/shared-workflows/.github/workflows/C:\work\repos\shared-workflows\.github\workflows\react-on-ghpages.yaml@main
    with:
      github-repository: ${GITHUB_REPOSITORY}
      working-directory: tictactoe
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
